BackBundle\Entity\User:
    type: entity
    table: user
    id:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: userId
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        surname:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
