BackBundle\Entity\Video:
    type: entity
    table: video
    indexes:
        fk_video_user:
            columns:
                - userId
    id:
        videoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: videoId
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        status:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        videopath:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: videoPath
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                userId:
                    referencedColumnName: userId
            orphanRemoval: false
    lifecycleCallbacks: {  }
