default_index:
    path:   /
    defaults: {_controller: "AppBundle:Default:index"}
    methods: GET

default_pruebas:
    path:   /pruebas
    defaults: {_controller: "AppBundle:Default:test"}
    methods: GET