user_create:
    path: /create
    defaults: {_controller: AppBundle:User:createUser}
    methods: POST
    
user_update:
    path: /update
    defaults: {_controller: AppBundle:User:updateUser}
    methods: POST
    
user_upload_image:
    path: /updateImage
    defaults: {_controller: AppBundle:User:updateImage}
    methods: POST
    
user_channel_videos:
    path: /channel/{userid}
    defaults: {_controller:AppBundle:User:channel, userid:null}
    methods: GET