video_create:
    path: /create
    defaults: {_controller: AppBundle:Video:createVideo}
    methods: POST
    
video_update:
    path: /update/{videoid}
    defaults: {_controller: AppBundle:Video:updateVideo, videoid:null}
    methods: POST
    
video_upload_files:
    path: /uploadFiles/{videoid}
    defaults: {_controller: AppBundle:Video:uploadFiles, videoid:null}
    methods: POST
    
video_list:
    path: /list
    defaults: {_controller: AppBundle:Video:videoList}
    methods: GET